import { Header } from '@/components/layout/header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Yumemi Front-end Coding Examination',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta
          name="apple-mobile-web-app-title"
          content="Yumemi Front-end Coding Examination"
        />
      </head>
      <body className="font-sans antialiased bg-slate-50 dark:bg-slate-900 text-black dark:text-white">
        <Header />
        {children}
      </body>
    </html>
  );
}
